sudo: 'required'

services:
  - 'docker'

before_script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
  - 'make build'
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      make publish ;
    fi
